SELECT nombre FROM producto;
SELECT nombre,precio FROM producto;
SELECT * FROM producto;
SELECT nombre,precio, FORMAT(precio*1.05,2)AS 'precio en dólares' FROM producto;
SELECT nombre AS 'nombre del producto',precio AS 'euros', FORMAT(precio*1.05,2)AS 'dólares norteamericanos' FROM producto;
SELECT UCASE(nombre)AS 'NOMBRE',precio from producto;
SELECT LCASE(nombre)AS 'nombre',precio from producto;
SELECT nombre,SUBSTR(UCASE(nombre),1,2) FROM fabricante;
SELECT nombre,ROUND(precio,1) FROM producto;
SELECT nombre,TRUNCATE(precio,0) FROM producto;
SELECT codigo_fabricante FROM producto;
SELECT DISTINCT(codigo_fabricante) FROM producto;
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre,precio FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante WHERE codigo BETWEEN 4 AND 6;
SELECT * FROM producto WHERE precio ORDER BY precio ASC LIMIT 1;
SELECT * FROM producto WHERE precio ORDER BY precio DESC LIMIT 1;
SELECT * FROM producto WHERE codigo_fabricante =2;
SELECT producto.nombre,producto.precio,fabricante.nombre FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo;