SELECT nombre FROM producto;
SELECT nombre,precio FROM producto;
SELECT * FROM producto;
SELECT nombre,precio, FORMAT(precio*1.05,2)AS 'precio en dólares' FROM producto;
SELECT nombre AS 'nombre del producto',precio AS 'euros', FORMAT(precio*1.05,2)AS 'dólares norteamericanos' FROM producto;
SELECT UCASE(nombre)AS 'NOMBRE',precio from producto;
SELECT LCASE(nombre)AS 'nombre',precio from producto;
SELECT nombre,SUBSTR(UCASE(nombre),1,2) FROM fabricante;
SELECT nombre,ROUND(precio,1) FROM producto;
SELECT nombre,TRUNCATE(precio,0) FROM producto;
SELECT codigo_fabricante FROM producto;
SELECT DISTINCT(codigo_fabricante) FROM producto;
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre,precio FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante WHERE codigo BETWEEN 4 AND 6;
SELECT * FROM producto WHERE precio ORDER BY precio ASC LIMIT 1;
SELECT * FROM producto WHERE precio ORDER BY precio DESC LIMIT 1;
SELECT * FROM producto WHERE codigo_fabricante =2;
SELECT producto.nombre,producto.precio,fabricante.nombre FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo;
SELECT producto.nombre,producto.precio,fabricante.nombre FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo ORDER BY fabricante.nombre ;
SELECT producto.codigo,producto.nombre,fabricante.codigo,fabricante.nombre FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo;
SELECT producto.nombre,precio,fabricante.nombre FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo ORDER BY precio ASC LIMIT 1;
SELECT producto.nombre,precio,fabricante.nombre FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo ORDER BY precio DESC LIMIT 1;
SELECT producto.*, fabricante.nombre from producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = 'Lenovo';
SELECT producto.*, fabricante.nombre from producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = 'Crucial' AND precio >200;
SELECT producto.*, fabricante.nombre from producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = 'Asus' OR fabricante.nombre='Hewlett-Packard' OR fabricante.nombre='Seagate';
SELECT producto.*, fabricante.nombre from producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre IN ('Asus','Hewlett-Packard','Seagate');
SELECT producto.nombre,precio FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre LIKE "%e";
SELECT producto.nombre,precio FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre LIKE "%w%";
SELECT producto.nombre,precio,fabricante.nombre FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE precio>=180 ORDER BY precio DESC, producto.nombre ASC;
SELECT fabricante.nombre,fabricante.codigo FROM fabricante INNER JOIN producto ON fabricante.codigo = producto.codigo_fabricante;
SELECT fabricante.nombre, producto.nombre FROM fabricante LEFT JOIN producto ON fabricante.codigo = producto.codigo_fabricante;
SELECT fabricante.nombre, producto.nombre FROM fabricante LEFT JOIN producto ON fabricante.codigo = producto.codigo_fabricante WHERE producto.codigo_fabricante IS NULL;
SELECT fabricante.nombre, producto.nombre FROM fabricante LEFT JOIN producto ON fabricante.codigo = producto.codigo_fabricante WHERE fabricante.nombre = 'Lenovo';
SELECT fabricante.nombre,producto.precio,producto.nombre FROM fabricante LEFT JOIN producto ON fabricante.codigo = producto.codigo_fabricante WHERE producto.precio = (SELECT MAX(producto.precio) FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = 'Lenovo');
SELECT producto.nombre,producto.precio FROM producto RIGHT JOIN fabricante ON producto.codigo_fabricante=fabricante.codigo WHERE fabricante.nombre = 'Lenovo' HAVING MAX(producto.precio);
SELECT producto.nombre,producto.precio FROM producto RIGHT JOIN fabricante ON producto.codigo_fabricante=fabricante.codigo WHERE fabricante.nombre = 'Hewlett-Packard' HAVING MIN(producto.precio);